from django.db import models
from django.conf import settings

class Report(models.Model):
    """
    Model to store the reports generated by users.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='reports',
        help_text="The user who generated this report."
    )
    title = models.CharField(
        max_length=200,
        help_text="A title for the report."
    )
    content = models.TextField(
        help_text="The full content of the generated report."
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The date and time the report was generated."
    )

    def __str__(self):
        return f"Report for {self.user.username} at {self.created_at.strftime('%Y-%m-%d %H:%M')}"

    class Meta:
        ordering = ['-created_at']

class ChatSession(models.Model):
    """
    Model to store a chat session.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='chat_sessions'
    )
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"ChatSession for {self.user.username} - {self.title}"

    class Meta:
        ordering = ['-created_at']

class ChatMessage(models.Model):
    """
    Model to store a single chat message.
    """
    session = models.ForeignKey(
        ChatSession,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    message = models.TextField()
    is_user_message = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{'User' if self.is_user_message else 'AI'} message in session {self.session.id}"

    class Meta:
        ordering = ['created_at']
