# Generated by Django 5.2.8 on 2025-11-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_token_expires',
        ),
    ]
