# Generated by Django 5.2.8 on 2025-11-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_verified_for_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
