# Generated by Django 5.2.8 on 2025-11-12 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A title for the report.', max_length=200)),
                ('content', models.TextField(help_text='The full content of the generated report.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the report was generated.')),
                ('user', models.ForeignKey(help_text='The user who generated this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
